# Generated by Django 4.2.5 on 2023-09-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_category_options_alter_dogs_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
    ]
