# Generated by Django 4.2.5 on 2023-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_rename_dogs_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birth_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
