# Generated by Django 4.2.5 on 2023-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_alter_dog_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
